package battletanks.game;

public enum INPUT_TYPE {
    LEFT_PRESSED, LEFT_RELEASED,
    RIGHT_PRESSED, RIGHT_RELEASED,
    FORWARD_PRESSED, FORWARD_RELEASED,
    BACKWARD_PRESSED, BACKWARD_RELEASED,
    FIRE_PRESSED, FIRE_RELEASED,
    PERSPECTIVE
    
}